apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: customer-a-dev

namePrefix: customer-a-dev-

patchesStrategicMerge:
  - secret-patch.yaml

commonLabels:
  customer: customer-a
  environment: dev
  service: redis

