apiVersion: apps/v1
kind: Deployment
metadata:
  name: cagent
  namespace: vpcp-app
  labels:
    app: cagent
    project: vpcp-c-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cagent
  template:
    metadata:
      labels:
        app: cagent
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: cagent-sa
      containers:
      - name: cagent
        image: 187091248012.dkr.ecr.us-east-1.amazonaws.com/vpcp/cagent:latest
        ports:
        - containerPort: 3000
          name: http
        envFrom:
        - configMapRef:
            name: cagent-config
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: database-password
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 180
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 180
          periodSeconds: 10
          timeoutSeconds: 10
          failureThreshold: 3