apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: vpcp-app
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
          name: redis
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        - --save
        - "900"
        - "1"
        - "300"
        - "10"
        - "60"
        - "10000"
        - --dir
        - /tmp
        - --dbfilename
        - dump.rdb
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secret
              key: redis-password
        - name: REDIS_MAXMEMORY
          value: "1gb"
        - name: REDIS_MAXMEMORY_POLICY
          value: "allkeys-lru"
        resources:
          requests:
            cpu: 512m
            memory: 2048Mi
          limits:
            cpu: 1024m
            memory: 4096Mi
        livenessProbe:
          exec:
            command:
            - redis-cli
            - --raw
            - incr
            - ping
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 5
        readinessProbe:
          exec:
            command:
            - redis-cli
            - --raw
            - incr
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5