apiVersion: v1
kind: ConfigMap
metadata:
  name: cagent-config
  namespace: vpcp-app
data:
  # Basic configuration
  NODE_ENV: "production"
  PORT: "3000"
  CORS_ORIGINS: "*"
  IFRAME_ORIGINS: "*"
  
  # Database configuration
  DATABASE_TYPE: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "postgres-service.vpcp-app.svc.cluster.local"
  DATABASE_NAME: "cagent"
  DATABASE_USER: "cagent_app"

  # Flowise configuration
  FLOWISE_SECRETKEY_OVERWRITE: "myencryptionkey"
  FLOWISE_FILE_SIZE_LIMIT: "256mb"
  STORAGE_TYPE: "local"
  APIKEY_STORAGE_TYPE: "db"
  
  # Document store configuration
  VITE_DOCUMENT_STORE_TYPE: "s3"
  VITE_DOCUMENT_STORE_BASE_URL: "http://s3-explorer-service.vpcp-app.svc.cluster.local:3001"
  
  # Authentication
  LOGIN_TYPE: "token"
  ACCESS_TOKEN_SECRET: "3d0f3b54d4f212522429e7d2b88486e6f6a7b76d4e03f6f69b0f4d913f0bc29d1f6f0a89d7c45d2f3f2d6c2f0a89d7c45d2f3f2d6c2f0a89d7c45d2f3f2d6c2"
  REFRESH_TOKEN_SECRET: "9a8f7e6d5c4b3a2918273645564738291a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0t1u2v3w4x5y6z7a8b9c0d1e2f3g4h5i6j7k8l9m0n1o2p3q4r5s6t"
  
  # Meilisearch configuration
  MEILISEARCH_HOST: "meilisearch.cagent.internal:7700"
  MEILISEARCH_API_KEY: "izSd5NSss903XQTra"
  
  # S3 configuration
  S3_STORAGE_REGION: "ap-southeast-1"
  S3_STORAGE_BUCKET_NAME: "ndthuat-lab"
  
  # Health check configuration
  HEALTH_CHECK_PATH: "/api/v1/ping"
  HEALTH_CHECK_INTERVAL: "30s"
  HEALTH_CHECK_TIMEOUT: "10s"
  HEALTH_CHECK_RETRIES: "3"
  HEALTH_CHECK_START_PERIOD: "40s"
  
  # Performance configuration
  CLUSTER_RATELIMIT_POINTS: "60"
  NODE_OPTIONS: "--expose-gc --max-old-space-size=4096"
  FORCE_GC: "true"

  # Knowledge base configuration
  SEED_KNOWLEDGE_BASE_ID: "8DQRAEW169"
  SEED_DATA_SOURCE_IDS: "49HKSV8YA6"
  SEED_FOLDER_NAME: "cagent-learnaws-click/"
  SEED_INDEX_NAME: "data"