apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: vpcp-app
data:
  # PostgreSQL configuration
  POSTGRES_DB: "cagent"
  POSTGRES_USER: "cagent_app"
  PGDATA: "/var/lib/postgresql/data/pgdata"
  
  # Performance tuning
  POSTGRES_SHARED_BUFFERS: "256MB"
  POSTGRES_EFFECTIVE_CACHE_SIZE: "1GB"
  POSTGRES_MAINTENANCE_WORK_MEM: "64MB"
  POSTGRES_CHECKPOINT_COMPLETION_TARGET: "0.9"
  POSTGRES_WAL_BUFFERS: "16MB"
  POSTGRES_DEFAULT_STATISTICS_TARGET: "100"
  POSTGRES_RANDOM_PAGE_COST: "1.1"
  POSTGRES_EFFECTIVE_IO_CONCURRENCY: "200"
  POSTGRES_WORK_MEM: "4MB"
  POSTGRES_MIN_WAL_SIZE: "1GB"
  POSTGRES_MAX_WAL_SIZE: "4GB"
  
  # Connection settings
  POSTGRES_MAX_CONNECTIONS: "100"
  POSTGRES_SHARED_PRELOAD_LIBRARIES: "pg_stat_statements" 