apiVersion: v1
kind: ConfigMap
metadata:
  name: s3-explorer-config
  namespace: vpcp-app
data:
  # Basic configuration
  NODE_ENV: "production"
  PORT: "3001"
  
  # S3 configuration
  S3_STORAGE_BUCKET_NAME: "ndthuat-lab"
  S3_STORAGE_REGION: "ap-southeast-1"
  AWS_REGION: "ap-southeast-1"
  
  # Redis configuration
  REDIS_HOST: "redis-service.vpcp-app.svc.cluster.local"
  REDIS_PORT: "6379"
  
  # Database configuration
  DATABASE_TYPE: "postgres"
  DATABASE_PORT: "5432"
  DATABASE_HOST: "postgres-service.vpcp-app.svc.cluster.local"
  DATABASE_NAME: "cagent"
  DATABASE_USER: "cagent_app"
  
  # External services
  BASE_URL: "http://3.231.34.3:8001"
  X_AUTH_SECRET_KEY: "tX5YKLeoCEBDYehSUjSDrFAqqbPIwpO3h52A1ZI7hBPjJWrX4zkMEZLAQDOD"
  BASE_URL_AI_SERVICE: "http://3.231.34.3:8001"
  
  # Trigger configuration
  TRIGGER_SECRET_KEY: "tr_prod_4oudPjBOD2QnEMNCbXgb"
  TRIGGER_API_URL: "https://trigger.1882.studio.ai.vn"
  
  # File and search configuration
  FILE_HOST: ""
  MEILISEARCH_HOST: "https://search.cmcts1.studio.ai.vn"
  MEILISEARCH_API_KEY: "6503e9ce62dfbdd119ebc9819821a85948eeffcfe3b502c35ab1765c225b9aae"
  
  # Crawl configuration
  CRAWL_BASE_URL: "https://firecrawl.1882.studio.ai.vn"
  DRIVE_REDIRECT_URI: "https://stock.cmcts.ai/c-agent/document-stores-new"
  
  # AWS OpenSearch configuration
  COLLECTION_ARN: "arn:aws:aoss:us-east-1:187091248012:collection/hjrorw4a5fdfg1fwhg28"
  BUCKET_OWNER_ACCOUNT_ID: "187091248012"
  ROLE_ARN: "arn:aws:iam::187091248012:role/VPCPCAgentBedrock"