apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-agent
  namespace: argocd
spec:
  description: AI Agent Application Project
  sourceRepos:
    - 'https://github.com/thuatnd-rk/devops-learning-portfolio'
    - 'https://github.com/thuatnd-rk/devops-learning-portfolio.git'
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'