[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf
    HTTP_Server  On
    HTTP_Listen  0.0.0.0
    HTTP_Port    2020

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    #Path              /var/lib/docker/containers/de8c0e201d59a274f14c65e9d1f35f17ea5dfe1ca89ad6d63881857b22f9aed8/de8c0e201d59a274f14c65e9d1f35f17ea5dfe1ca89ad6d63881857b22f9aed8-json.log
    Parser            docker
    Docker_Mode       On
    Tag               docker.*
    Refresh_Interval  5
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Read_from_Head    On
    #Exclude_Path      /var/lib/docker/containers/04574acb13f054ddfeee4410434eb9b2f67c676dca6d1236854d34b7821883f1/*

[FILTER]
    Name    lua
    Match   *
    script  /fluent-bit/etc/get_container_name.lua
    call    add_container_name

# [FILTER]
#     Name    grep
#     Match   *
#     Regex   log FLOW_COMPLETION_TIME.*

[FILTER]
    Name    modify
    Match   *
    Condition Key_exists log
    Condition Key_value_matches log TOKEN_USAGE_METRICS
    Add     metric_type token_usage
    Add     log_source flowise


[OUTPUT]
    Name  loki
    Match *
    Host  loki 
    Port  3100
    URI   /loki/api/v1/push
    Labels container_id=$container_id,container_name=$container_name,metric_type=$metric_type