apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: customer-a-production

namePrefix: customer-a-production-

patchesStrategicMerge:
  - secret-patch.yaml

commonLabels:
  customer: customer-a
  environment: production
  service: redis

