global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'trihoangminh50@gmail.com'
  smtp_auth_username: 'trihoangminh50@gmail.com'
  smtp_auth_password: 'temp_holder' # khi nao dung se loi cai mk ra
  smtp_require_tls: true

route:
  receiver: 'email-alert'
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'email-alert'
    email_configs:
      - to: 'trihoangminh50@gmail.com'
        text: |
          Alert Details:
          {{ range .Alerts }}
          - Alert: {{ .Annotations.summary }}
          - Description: {{ .Annotations.description }}
          - Started: {{ .StartsAt }}
          {{ end }}