apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: chatbot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
  - secretKey: postgres_password
    remoteRef:
      key: ndthuat-k8s
      property: postgres_password
  - secretKey: postgres_username
    remoteRef:
      key: ndthuat-k8s
      property: postgres_username
  - secretKey: postgres_database
    remoteRef:
      key: ndthuat-k8s
      property: postgres_database
