apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgbouncer-secret
  namespace: chatbot
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: pgbouncer-secret
    creationPolicy: Owner
  data:
  - secretKey: DB_USER
    remoteRef:
      key: ndthuat-k8s
      property: postgres_username
  - secretKey: DB_PASSWORD
    remoteRef:
      key: ndthuat-k8s
      property: postgres_password
  - secretKey: DB_NAME
    remoteRef:
      key: ndthuat-k8s
      property: postgres_database


