# projects/ai-agent-eks/argocd/applications/customer-a/frontend-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-a-frontend
  namespace: argocd
  labels:
    customer: customer-a
    service: frontend
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai-agent
  source:
    repoURL: https://github.com/thuatnd-rk/customer-a-frontend  # Repo riêng cho frontend
    targetRevision: main
    path: kubernetes  # Path trong repo chứa manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-a
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true