# projects/ai-agent-eks/argocd/applications/customer-a/postgres-app-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-a-postgres-dev
  namespace: argocd
  labels:
    customer: customer-a
    service: postgres
    environment: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai-agent
  source:
    repoURL: https://github.com/thuatnd-rk/devops-learning-portfolio
    targetRevision: main
    path: projects/ai-agent-eks/kubernetes/database/postgres/overlays/customer-a-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-a-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

