# projects/ai-agent-eks/argocd/applications/customer-a/redis-app-production.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: customer-a-redis-production
  namespace: argocd
  labels:
    customer: customer-a
    service: redis
    environment: production
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: ai-agent
  source:
    repoURL: https://github.com/thuatnd-rk/devops-learning-portfolio
    targetRevision: main
    path: projects/ai-agent-eks/kubernetes/database/redis/overlays/customer-a-production
  destination:
    server: https://kubernetes.default.svc
    namespace: customer-a-production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

