apiVersion: v1
kind: Service
metadata:
  name: cagent-service
  namespace: vpcp-app
  labels:
    app: cagent
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: cagent