apiVersion: v1
kind: Service
metadata:
  name: s3-explorer-service
  namespace: vpcp-app
  labels:
    app: s3-explorer
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: s3-explorer